#! /usr/bin/env sh

JNA_VERSION=5.12.1
export JNA_VERSION=5.12.1

export GITHUB_TAG=$(git describe --tags --abbrev=0 | sed 's|i2p||g' | tr -d [a-z-])
if [ -z "$VERSIONMAJOR" ]; then
    VERSIONMAJOR=$(echo "$GITHUB_TAG" | cut -d . -f 1)
fi
if [ -z "$VERSIONMINOR" ]; then
    VERSIONMINOR=$(echo "$GITHUB_TAG" | cut -d . -f 2)
fi
if [ -z "$VERSIONBUILD" ]; then
    VERSIONBUILD=$(echo "$GITHUB_TAG" | cut -d . -f 3)
fi
if [ -z "$VERSIONMAJOR" ]; then
    VERSIONMAJOR=2
fi
if [ -z "$VERSIONMINOR" ]; then
    VERSIONMINOR=6
fi
if [ -z "$VERSIONBUILD" ]; then
    VERSIONBUILD=0
fi
I2P_VERSION="$VERSIONMAJOR.$VERSIONMINOR.$VERSIONBUILD"
export I2P_VERSION="$VERSIONMAJOR.$VERSIONMINOR.$VERSIONBUILD"
# Comment this out to build from an alternate branch or
# the tip of the master branch.
#VERSION=i2p-2.4.0
#export VERSION=i2p-2.4.0
VERSION="i2p-$GITHUB_TAG"
export VERSION="i2p-$GITHUB_TAG"

I2PFIREFOX_VERSION="$VERSIONMAJOR.$VERSIONMINOR.2"
export I2PFIREFOX_VERSION="$VERSIONMAJOR.$VERSIONMINOR.2"
echo "I2P version $I2P_VERSION"
echo "Tag $VERSION"
echo "I2P Firefox Profile version $I2PFIREFOX_VERSION"