#! /usr/bin/env sh

JNA_VERSION=5.11.0
export JNA_VERSION=5.11.0

#Comment this out to build from an alternate branch or
# the tip of the master branch.
VERSIONMAJOR=1
VERSIONMINOR=7
VERSIONBUILD=7
I2P_VERSION="$VERSIONMAJOR.$VERSIONMINOR.$VERSIONBUILD"
export I2P_VERSION="$VERSIONMAJOR.$VERSIONMINOR.$VERSIONBUILD"
VERSION=i2p-jpackage-1.7.1
export VERSION=i2p-jpackage-1.7.1

#Uncomment this to build from the tip of the master.
#I2P_VERSION=1.8.0
#export I2P_VERSION=1.8.0
#VERSION=master
#export VERSION="$VERSION"
