#! /usr/bin/env sh


#Comment this out to build from an alternate branch or
# the tip of the master branch.
I2P_VERSION=1.6.1
export I2P_VERSION=1.6.1
VERSION=i2p-"$I2P_VERSION"
export VERSION="$VERSION"

#Uncomment this to build from the tip of the master.
#I2P_VERSION=0.9.50
#export I2P_VERSION=0.9.50
#VERSION=master
#export VERSION="$VERSION"
